version: '3.7'

services:
  ipfs:
    image: ipfs/go-ipfs:v0.6.0
    volumes:
      - "../../ipfs/export:/export"
      - "../../ipfs/data/ipfs:/data/ipfs"
    ports:
      - 5001:5001
      - 4001:4001
      - 8080:8080

  api:
    build: ./
    environment: ["PORT:8000"]
    command: gunicorn kamui.wsgi:application --bind 0.0.0.0:$PORT
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

